// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  bandId: __t.u64().primaryKey(),
  name: __t.string(),
  leader: __t.identity(),
  styleTag: __t.string(),
  tokensTreasury: __t.u64(),
  totalBattles: __t.u32(),
  battleWins: __t.u32(),
  battleLosses: __t.u32(),
  tournamentTitles: __t.u32(),
  totalTournaments: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
