// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import InstrumentRole from "./instrument_role_type";


export default __t.object("BandMembership", {
  membershipId: __t.u64(),
  bandId: __t.u64(),
  memberIdentity: __t.option(__t.identity()),
  displayName: __t.string(),
  get role() {
    return InstrumentRole;
  },
  skillRating: __t.u32(),
  isNpc: __t.bool(),
  joinedAt: __t.timestamp(),
  active: __t.bool(),
});


