// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BattleState from "./battle_state_type";


export default __t.row({
  battleId: __t.u64().primaryKey(),
  bandAId: __t.u64(),
  bandBId: __t.u64(),
  entryFee: __t.u64(),
  prizePool: __t.u64(),
  bandAScore: __t.u64(),
  bandBScore: __t.u64(),
  roundsPlayed: __t.u32(),
  get state() {
    return BattleState;
  },
  winnerBandId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
