// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import InstrumentRole from "./instrument_role_type";
import CharacterStyle from "./character_style_type";
import InstrumentOwnership from "./instrument_ownership_type";

export default {
  username: __t.string(),
  get style() {
    return CharacterStyle;
  },
  get preferredRole() {
    return InstrumentRole;
  },
  get instruments() {
    return __t.array(InstrumentOwnership);
  },
};
