// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `InstrumentRole`.
const InstrumentRole = __t.enum("InstrumentRole", {Singer: __t.unit(),
  LeadGuitarist: __t.unit(),
  RhythmGuitarist: __t.unit(),
  Bassist: __t.unit(),
  Drummer: __t.unit(),
  Keyboardist: __t.unit(),
  Violinist: __t.unit(),
  Saxophonist: __t.unit(),
  Trumpeter: __t.unit(),
  DJ: __t.unit(),
  Producer: __t.unit(),
  Percussionist: __t.unit(),
  SoundEngineer: __t.unit(),
});

export default InstrumentRole;


