// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import InstrumentRole from "./instrument_role_type";


export default __t.object("InstrumentOwnership", {
  get role() {
    return InstrumentRole;
  },
  mastery: __t.u32(),
  favoriteInstrumentName: __t.string(),
});


