// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import CharacterStyle from "./character_style_type";
import InstrumentOwnership from "./instrument_ownership_type";


export default __t.object("PlayerProfile", {
  identity: __t.identity(),
  username: __t.string(),
  get style() {
    return CharacterStyle;
  },
  level: __t.u32(),
  xp: __t.u64(),
  totalEarnings: __t.u64(),
  rockTokens: __t.u64(),
  get instrumentsOwned() {
    return __t.array(InstrumentOwnership);
  },
  soloStageIndex: __t.u8(),
  totalBattles: __t.u32(),
  battleWins: __t.u32(),
  totalTournaments: __t.u32(),
  tournamentTitles: __t.u32(),
  currentBand: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});


