// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  milestoneId: __t.u64().primaryKey(),
  identity: __t.identity(),
  stageIndex: __t.u8(),
  stageName: __t.string(),
  performanceScore: __t.u32(),
  rewardTokens: __t.u64(),
  completedAt: __t.timestamp(),
});
